### ISSUE TITLE
struct.error: unpack requires a buffer of 2 bytes

### ISSUE THREAD

**Issue by WololoJ** [adafruit/Adafruit_UTI165_Camera#2]
I've purchased an uti165k camera, I got an error says 

Traceback (most recent call last):
  File "opencv_uti165k.py", line 55, in <module>
    print(struct.unpack("h", frame[320][0])[0]/10)
struct.error: unpack requires a buffer of 2 bytes

When I run the opencv_uti165k.py on my mac.

If I comment out the code for calculation temperature, then the camera stream can be displayed correctly.

**Comment by Ramavarapu** [comment]
I just got the UTi165K camera today.  I am running into the same issue on my Mac.  

But when I run the Python Code within Thonny on my Raspberry Pi 4, everything seems to work fine.  Just saying!

**Comment by andrewhw** [comment]
Has something perhaps changed in opencv's interface?

When I run the code that attempts to unpack the short, I get the error mentioned in this thread.

When I attempt to print out what is being passed to unpack, namely
```python
print(frame[320][0])
print(type(frame[320][0]))
```
I get the following:
```python
[  0 255   0]  
<class 'numpy.ndarray'>
```

I am surprised that a three element numpy array is being unpacked via struct.unpack, as I would have expected a byte string, and a two-byte one at that.

Has something perhaps changed in openCV somehow?  I'm running OpenCV 4.2.0 on my Mac, and I seem to have 4.3.0 on Windows (python module versions).

What was the data type that you were unpacking previously?


In addition (not sure if you would rather have this copied to the other thread), everything works for me on Windows as well as on Mac.  Haven't tried it on Linux.

On Windows I do get these two lines of warning, but then it just carries on, opens a window, and streams the frames to it:
```
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (436) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (436) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
```

**Comment by andrewhw** [comment]
Yep - at the moment, I am guessing that at some point, OpenCV changed the way that
    ```
    cam.set(cv2.CAP_PROP_CONVERT_RGB, 0)
    ```
is working, as this doesn't actually seem to take the camera out of RGB mode.
