### ISSUE TITLE
Windows Fail 

### ISSUE THREAD

**Issue by hfmartinez** [adafruit/Adafruit_UTI165_Camera#3]
Currently the script is running on windows, 

the connection is opened but the program remains in "Failed to fetch frame" and does not show anything in the image viewer

![image](https://user-images.githubusercontent.com/49379467/85746126-d6685700-b6cb-11ea-86ad-f4fc26726bd9.png)

**Comment by ladyada** [comment]
correct, it does not work on windows for some reason. it works on linux and mac
https://learn.adafruit.com/uti165-thermal-fever-scanner-camera
if you have a fix please submit a PR :)
