### ISSUE TITLE
Raw thermal data

### ISSUE THREAD

**Issue by rah59** [adafruit/Adafruit_UTI165_Camera#4]
How did you guys capture the raw thermal data from the camera?

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_UTI165_Camera/blob/master/raw_thermal.py#L63

**Comment by rah59** [comment]
Thanks, ladyada. Perhaps I am missing something. How did the thermal data from the camera get streamed to the CSV file? Can we stream data from the camera directly?

**Comment by ladyada** [comment]
usb data capture device

**Comment by rah59** [comment]
I bought this camera from Adafruit. It's a great camera. However, i am unsure as to how to make it work with python. OpenCV does provide the thermal image but I need the temp information. Not sure if you have tested any library that can connect to the camera and control it. It does show up as a UVC camera in device manager. Is it possible to get data without the usb data capture device? Thanks for your help.

**Comment by ladyada** [comment]
https://learn.adafruit.com/uti165-thermal-fever-scanner-camera/python-software

**Comment by ladyada** [comment]
max temp is here https://github.com/adafruit/Adafruit_UTI165_Camera/blob/master/opencv_uti165k.py#L53

**Comment by rah59** [comment]
That line fails for some reason.

**Comment by ladyada** [comment]
you can subscribe to https://github.com/adafruit/Adafruit_UTI165_Camera/issues/2 - we dont have a fix right now :)

**Comment by rah59** [comment]
Ladyada, in your video https://learn.adafruit.com/uti165-thermal-fever-scanner-camera/python-software , you mention quickly how you are able to get temperature information from the camera. I was quite not able to grasp how you did that. Can you please provide information on how you are able to retrieve temperature information? Thanks in advance.
