### ISSUE TITLE
This is yielding a negative number about 12-14 less than the Celsius reading from the screen

### ISSUE THREAD

**Issue by mrglover** [adafruit/Adafruit_UTI165_Camera#5]
The following line is yielding a temp reading that is around 12-14 lower than the actual temp reading on the screen. Also, I notice that it doesn't update with some of the fluctuation of readings on the screen. See Screenshot below for my output vs. camera.

https://github.com/adafruit/Adafruit_UTI165_Camera/blob/5db633d69c03dd5bcc9c0d2158a3dcb1b6f56c85/opencv_uti165k.py#L53

![image](https://user-images.githubusercontent.com/938230/89693856-9bf5fa80-d8c4-11ea-849a-0a9218825923.png)

Thank you so much in advance for your help on this. I haven't changed anything in the source so far.

**Comment by ladyada** [comment]
yeah it doesnt work. if you can figure it out please submit a PR

**Comment by mrglover** [comment]
@ladyada Was this ever working? Was there a specific version of OpenCV that actually worked.

@ljyang didnt you get this to work and read the correct temperature via python/opencv?

**Comment by ladyada** [comment]
i dont think it was ever working with opencv - we were able to get the display only - someone else tried adding the temperature

**Comment by mrglover** [comment]
Could not get this working on my macbook pro (some other issues must exist), but the code is pulling the correct temp now with the camera hooked up to my RaspberryPi 4 (2gb) running the newest Raspberry Pi OS (formerly Raspbian). @ljyang was able to get me the pip install for the opencv version he was using:

sudo pip3 install opencv-contrib-python==4.1.0.25

which ended up allowing the code in this repo to work perfectly.

Thanks for your help John (@ljyang)!

closing issue.

**Comment by harrisnisar** [comment]
I will also be trying this to see if it works. Will let you know.
